[package]
name = "ledger-rust-eip712"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
alloy-dyn-abi = { git = "https://github.com/Conflux-Chain/alloy-rs-core.git", rev = "8895f56", default-features = false, features = ["eip712"] }
alloy-primitives = { git = "https://github.com/Conflux-Chain/alloy-rs-core.git", rev = "8895f56", default-features = false }
alloy-sol-types = { git = "https://github.com/Conflux-Chain/alloy-rs-core.git", rev = "8895f56", default-features = false }

[target.'cfg(target_os = "nanox")'.dependencies]
bytes = { git = "https://github.com/Conflux-Chain/bytes.git", rev = "00bc7c3", default-features = false, features = ["extra-platforms"] }

[target.'cfg(not(target_os = "nanox"))'.dependencies]
bytes = { git = "https://github.com/Conflux-Chain/bytes.git", rev = "00bc7c3", default-features = false }

[features]
default = ["std"]
std = []
